name: CI
on:
  push:
    branches: [ main , master ]
  pull_request:
    branches: [ main , master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync -p 3.13
      - name: Mypy
        run: uv run mypy day_*/
      - name: pytest
        run: uv run pytest -s */*.py
      - name: lint
        run: uv run ruff check day_*
      - name: format
        run: uv run ruff format --check day_*
